CREATE TABLE churn_predictions (
    customerid INTEGER PRIMARY KEY,
    surname TEXT,
    creditscore INTEGER,
    age INTEGER,
    tenure INTEGER,
    balance DOUBLE PRECISION,
    num_of_product INTEGER,
    hascrcard INTEGER,
    isactivemember INTEGER,
    estimatedsalary DOUBLE PRECISION,
    balancesalary DOUBLE PRECISION,
    tenureage DOUBLE PRECISION,
    scoreage DOUBLE PRECISION,
    tenure_age DOUBLE PRECISION,
    tenure_salary DOUBLE PRECISION,
    score_age DOUBLE PRECISION,
    score_salary DOUBLE PRECISION,
    newAge DOUBLE INTEGER,
    newCreditScore INTEGER,
    AgeScore INTEGER,
    BalanceScore INTEGER,
    SalaryScore INTEGER,
    newEstimatedSalary DOUBLE PRECISION,
    score_balance DOUBLE PRECISION,
    age_balance DOUBLE PRECISION,
    balance_salary DOUBLE PRECISION,
    age_hascrcard DOUBLE PRECISION,
    product_utilization_rate_by_year DOUBLE PRECISION,
    product_utilization_rate_by_salary DOUBLE PRECISION,
    countries_monthly_average_salaries DOUBLE PRECISION,
    Germany BOOLEAN,
    Spain BOOLEAN,
    Female BOOLEAN,
    Male BOOLEAN,
    churnprediction DOUBLE PRECISION; 
);
